rootProject.name = "Vulture-Station"
include("utilities")
include("database")
include("sdk")
include("external-oled-display-on-pi")
include("user-server")
include("nas-server")
include("quic-protocol-sdk")
include("ddns-server")
include("system_monitor")